// <auto-generated />
using System;
using FtpPoller.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FtpPoller.Data.Migrations
{
    [DbContext(typeof(FtpPollerContext))]
    [Migration("20230522141258_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FtpPoller.Data.Entities.File", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InsertedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("CopiedFiles");
                });

            modelBuilder.Entity("FtpPoller.Data.Entities.Payer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FolderDir")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SrcPassword")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SrcPort")
                        .HasColumnType("integer");

                    b.Property<string>("SrcServer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SrcUserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Payers");
                });
#pragma warning restore 612, 618
        }
    }
}
